# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: devnull03.qrate
PackageVersion: 0.6.0
InstallerType: msi
Scope: machine
ReleaseDate: 2026-09-29
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/devnull03/qrate/releases/download/v0.6.0/qrate-0.6.0-x86_64.msi
  InstallerSha256: 1C34D6B4AF49175ADAEB396CDC3C78921423506BD06642194784FBB02F81202F
  ProductCode: '{BD8ECA84-253B-448A-9E1B-16405F25A9EC}'
  AppsAndFeaturesEntries:
  - DisplayName: qrate
    Publisher: devnull03
    DisplayVersion: 0.6.0.0
    ProductCode: '{BD8ECA84-253B-448A-9E1B-16405F25A9EC}'
ManifestType: installer
ManifestVersion: 1.12.0
